name: Healthcheck

on:
  push:
    branches:
      - main
  schedule:
    - cron: "0 3 * * *"

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        package:
          - studiopoirierbailay.com
          - eliasrhouzlane.com
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js
        uses: actions/setup-node@v3
      - run: echo $(curl -s --head ${{ matrix.package }}) | grep "200 OK" > /dev/null
